/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 35.3.0 Tue Sep 30 11:01:48 2025.
 */

#include <string.h>
#include "CANFD_A2B.h"


canfd_a2_b_eamp_1_t 			EAMP_1;
canfd_a2_b_eamp_2_t 			EAMP_2;
canfd_a2_b_eamp_3_t 			EAMP_3;
canfd_a2_b_eamp_4_t 			EAMP_4;
canfd_a2_b_eamp_remote_diag_t 	EAMP_RemoteDiag;
canfd_a2_b_eamp_tx_t 			EAMP_TX;
canfd_a2_b_eamp_rx_t 			EAMP_RX;
canfd_a2_b_n_mm_eamp_t 			NMm_EAMP;
canfd_a2_b_diag_eamp_res_t 		Diag_EAMP_RES;
canfd_a2_b_diag_eamp_req_t 		Diag_EAMP_REQ;
canfd_a2_b_icc_ic_2_t 			ICC_IC_2;
canfd_a2_b_icc_ic_9_t 			ICC_IC_9;
canfd_a2_b_icc_ic_10_t 			ICC_IC_10;
canfd_a2_b_icc_ic_37_t 			ICC_IC_37;
canfd_a2_b_flzcu_9_t 			FLZCU_9;
canfd_a2_b_vcu_1_g_t 			VCU_1_G;
canfd_a2_b_obd_req_broadcast_t 	OBD_REQ_Broadcast;
canfd_a2_b_onebox_1_g_t 		ONEBOX_1_G;
canfd_a2_b_ems_1_g_t 			EMS_1_G;
canfd_a2_b_tms_1_t 				TMS_1;




static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int canfd_a2_b_eamp_1_pack(
    uint8_t *dst_p,
    canfd_a2_b_eamp_1_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->stat_ampvr_volume, 4u, 0xf0u);
    dst_p[0] |= pack_left_shift_u8(src_p->stat_amp_navi_volume, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->stat_amp_media_volume, 2u, 0xfcu);
    dst_p[1] |= pack_left_shift_u8(src_p->stat_amp_key_tone, 0u, 0x03u);
    dst_p[2] |= pack_left_shift_u8(src_p->stat_amp_sound_focus, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->stat_amp_phone_volume, 0u, 0x1fu);
    dst_p[3] |= pack_left_shift_u8(src_p->stat_amp_sound_effect_bass, 4u, 0xf0u);
    dst_p[3] |= pack_left_shift_u8(src_p->stat_amp_sound_effect, 0u, 0x0fu);
    dst_p[4] |= pack_left_shift_u8(src_p->stat_amp_sound_effect_treble, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u8(src_p->stat_amp_sound_effect_midrange, 0u, 0x0fu);
    dst_p[5] |= pack_left_shift_u8(src_p->stat_amp_sound_field_fader, 4u, 0xf0u);
    dst_p[5] |= pack_left_shift_u8(src_p->stat_amp_sound_field_balance, 0u, 0x0fu);
    dst_p[6] |= pack_left_shift_u8(src_p->stat_req_ampa2_btts_sound, 6u, 0xc0u);
    dst_p[6] |= pack_left_shift_u8(src_p->stat_req_ampa2_bvr_sound, 4u, 0x30u);
    dst_p[6] |= pack_left_shift_u8(src_p->stat_req_ampa2_b_navi_sound, 2u, 0x0cu);
    dst_p[6] |= pack_left_shift_u8(src_p->stat_req_ampa2_b_media_sound, 0u, 0x03u);
    dst_p[7] |= pack_left_shift_u8(src_p->stat_req_amp_alarm, 2u, 0xfcu);
    dst_p[7] |= pack_left_shift_u8(src_p->stat_req_ampa2_b_phone_sound, 0u, 0x03u);

    return (8);
}

int canfd_a2_b_eamp_1_unpack(
    canfd_a2_b_eamp_1_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->stat_ampvr_volume = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);
    dst_p->stat_amp_navi_volume = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->stat_amp_media_volume = unpack_right_shift_u8(src_p[1], 2u, 0xfcu);
    dst_p->stat_amp_key_tone = unpack_right_shift_u8(src_p[1], 0u, 0x03u);
    dst_p->stat_amp_sound_focus = unpack_right_shift_u8(src_p[2], 5u, 0xe0u);
    dst_p->stat_amp_phone_volume = unpack_right_shift_u8(src_p[2], 0u, 0x1fu);
    dst_p->stat_amp_sound_effect_bass = unpack_right_shift_u8(src_p[3], 4u, 0xf0u);
    dst_p->stat_amp_sound_effect = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->stat_amp_sound_effect_treble = unpack_right_shift_u8(src_p[4], 4u, 0xf0u);
    dst_p->stat_amp_sound_effect_midrange = unpack_right_shift_u8(src_p[4], 0u, 0x0fu);
    dst_p->stat_amp_sound_field_fader = unpack_right_shift_u8(src_p[5], 4u, 0xf0u);
    dst_p->stat_amp_sound_field_balance = unpack_right_shift_u8(src_p[5], 0u, 0x0fu);
    dst_p->stat_req_ampa2_btts_sound = unpack_right_shift_u8(src_p[6], 6u, 0xc0u);
    dst_p->stat_req_ampa2_bvr_sound = unpack_right_shift_u8(src_p[6], 4u, 0x30u);
    dst_p->stat_req_ampa2_b_navi_sound = unpack_right_shift_u8(src_p[6], 2u, 0x0cu);
    dst_p->stat_req_ampa2_b_media_sound = unpack_right_shift_u8(src_p[6], 0u, 0x03u);
    dst_p->stat_req_amp_alarm = unpack_right_shift_u8(src_p[7], 2u, 0xfcu);
    dst_p->stat_req_ampa2_b_phone_sound = unpack_right_shift_u8(src_p[7], 0u, 0x03u);

    return (0);
}

bool canfd_a2_b_eamp_1_stat_ampvr_volume_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_1_stat_amp_navi_volume_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_1_stat_amp_media_volume_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_eamp_1_stat_amp_key_tone_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_1_stat_amp_sound_focus_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool canfd_a2_b_eamp_1_stat_amp_phone_volume_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

bool canfd_a2_b_eamp_1_stat_amp_sound_effect_bass_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_1_stat_amp_sound_effect_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_1_stat_amp_sound_effect_treble_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_1_stat_amp_sound_effect_midrange_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_1_stat_amp_sound_field_fader_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_1_stat_amp_sound_field_balance_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_1_stat_req_ampa2_btts_sound_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_1_stat_req_ampa2_bvr_sound_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_1_stat_req_ampa2_b_navi_sound_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_1_stat_req_ampa2_b_media_sound_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_1_stat_req_amp_alarm_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_eamp_1_stat_req_ampa2_b_phone_sound_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int canfd_a2_b_eamp_2_pack(
    uint8_t *dst_p,
    canfd_a2_b_eamp_2_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->stat_amp_mute, 6u, 0xc0u);
    dst_p[0] |= pack_left_shift_u8(src_p->stat_amp_speed_volume, 3u, 0x38u);
    dst_p[0] |= pack_left_shift_u8(src_p->stat_amp_media_duck, 0u, 0x03u);
    dst_p[1] |= pack_left_shift_u8(src_p->stat_headrest_mode, 6u, 0xc0u);
    dst_p[1] |= pack_left_shift_u8(src_p->stat_amp_alarm_volume, 2u, 0x3cu);
    dst_p[1] |= pack_left_shift_u8(src_p->stat_amp_restore_defaults, 0u, 0x03u);
    dst_p[2] |= pack_left_shift_u8(src_p->stat_amp_sound_effect_mid_bass, 4u, 0xf0u);
    dst_p[2] |= pack_left_shift_u8(src_p->stat_amp_sound_effect_mega_bass, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->stat_surnd_fn_on_off, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->stat_virtual_sbwfr_on_off, 4u, 0x30u);
    dst_p[3] |= pack_left_shift_u8(src_p->stat_amp_sound_effect_mid_treble, 0u, 0x0fu);
    dst_p[4] |= pack_left_shift_u8(src_p->stat_amp_sound_bypass, 6u, 0xc0u);
    dst_p[4] |= pack_left_shift_u8(src_p->stat_amp_background_volume, 0u, 0x3fu);
    dst_p[5] |= pack_left_shift_u8(src_p->stat_amp_version, 2u, 0xfcu);
    dst_p[5] |= pack_left_shift_u8(src_p->stat_amp_pwr_rdy_sts, 0u, 0x03u);

    return (8);
}

int canfd_a2_b_eamp_2_unpack(
    canfd_a2_b_eamp_2_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->stat_amp_mute = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->stat_amp_speed_volume = unpack_right_shift_u8(src_p[0], 3u, 0x38u);
    dst_p->stat_amp_media_duck = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->stat_headrest_mode = unpack_right_shift_u8(src_p[1], 6u, 0xc0u);
    dst_p->stat_amp_alarm_volume = unpack_right_shift_u8(src_p[1], 2u, 0x3cu);
    dst_p->stat_amp_restore_defaults = unpack_right_shift_u8(src_p[1], 0u, 0x03u);
    dst_p->stat_amp_sound_effect_mid_bass = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->stat_amp_sound_effect_mega_bass = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->stat_surnd_fn_on_off = unpack_right_shift_u8(src_p[3], 6u, 0xc0u);
    dst_p->stat_virtual_sbwfr_on_off = unpack_right_shift_u8(src_p[3], 4u, 0x30u);
    dst_p->stat_amp_sound_effect_mid_treble = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->stat_amp_sound_bypass = unpack_right_shift_u8(src_p[4], 6u, 0xc0u);
    dst_p->stat_amp_background_volume = unpack_right_shift_u8(src_p[4], 0u, 0x3fu);
    dst_p->stat_amp_version = unpack_right_shift_u8(src_p[5], 2u, 0xfcu);
    dst_p->stat_amp_pwr_rdy_sts = unpack_right_shift_u8(src_p[5], 0u, 0x03u);

    return (0);
}

bool canfd_a2_b_eamp_2_stat_amp_mute_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_2_stat_amp_speed_volume_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool canfd_a2_b_eamp_2_stat_amp_media_duck_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_2_stat_headrest_mode_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_2_stat_amp_alarm_volume_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_2_stat_amp_restore_defaults_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_2_stat_amp_sound_effect_mid_bass_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_2_stat_amp_sound_effect_mega_bass_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_2_stat_surnd_fn_on_off_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_2_stat_virtual_sbwfr_on_off_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_2_stat_amp_sound_effect_mid_treble_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_2_stat_amp_sound_bypass_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_2_stat_amp_background_volume_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_eamp_2_stat_amp_version_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_eamp_2_stat_amp_pwr_rdy_sts_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int canfd_a2_b_eamp_3_pack(
    uint8_t *dst_p,
    canfd_a2_b_eamp_3_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->eamp_ampa2_benc_sound_fed, 6u, 0xc0u);
    dst_p[0] |= pack_left_shift_u8(src_p->eamp_ampkt_vvoice_volume_fed, 0u, 0x3fu);
    dst_p[1] |= pack_left_shift_u8(src_p->eamp_ampa2_b_chime_sound_fed, 6u, 0xc0u);
    dst_p[1] |= pack_left_shift_u8(src_p->eamp_ampenc_volume_fed, 0u, 0x3fu);
    dst_p[2] |= pack_left_shift_u8(src_p->stat_amp_sound_focus_2, 4u, 0xf0u);
    dst_p[2] |= pack_left_shift_u8(src_p->eamp_ampa2_bkt_vvoice_sound_fed, 0u, 0x07u);
    dst_p[3] |= pack_left_shift_u8(src_p->stat_amp_loudness, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->stat_amp_key_volume, 0u, 0x3fu);
    dst_p[4] |= pack_left_shift_u8(src_p->stat_amp_ex_soundmode, 5u, 0xe0u);
    dst_p[4] |= pack_left_shift_u8(src_p->stat_ampa2_benc_sound, 2u, 0x1cu);

    return (8);
}

int canfd_a2_b_eamp_3_unpack(
    canfd_a2_b_eamp_3_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->eamp_ampa2_benc_sound_fed = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->eamp_ampkt_vvoice_volume_fed = unpack_right_shift_u8(src_p[0], 0u, 0x3fu);
    dst_p->eamp_ampa2_b_chime_sound_fed = unpack_right_shift_u8(src_p[1], 6u, 0xc0u);
    dst_p->eamp_ampenc_volume_fed = unpack_right_shift_u8(src_p[1], 0u, 0x3fu);
    dst_p->stat_amp_sound_focus_2 = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->eamp_ampa2_bkt_vvoice_sound_fed = unpack_right_shift_u8(src_p[2], 0u, 0x07u);
    dst_p->stat_amp_loudness = unpack_right_shift_u8(src_p[3], 6u, 0xc0u);
    dst_p->stat_amp_key_volume = unpack_right_shift_u8(src_p[3], 0u, 0x3fu);
    dst_p->stat_amp_ex_soundmode = unpack_right_shift_u8(src_p[4], 5u, 0xe0u);
    dst_p->stat_ampa2_benc_sound = unpack_right_shift_u8(src_p[4], 2u, 0x1cu);

    return (0);
}

bool canfd_a2_b_eamp_3_eamp_ampa2_benc_sound_fed_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_3_eamp_ampkt_vvoice_volume_fed_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_eamp_3_eamp_ampa2_b_chime_sound_fed_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_3_eamp_ampenc_volume_fed_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_eamp_3_stat_amp_sound_focus_2_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_eamp_3_eamp_ampa2_bkt_vvoice_sound_fed_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool canfd_a2_b_eamp_3_stat_amp_loudness_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_eamp_3_stat_amp_key_volume_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_eamp_3_stat_amp_ex_soundmode_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool canfd_a2_b_eamp_3_stat_ampa2_benc_sound_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int canfd_a2_b_eamp_4_pack(
    uint8_t *dst_p,
    canfd_a2_b_eamp_4_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_left_shift_u8(src_p->stat_eamp_monitor1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->stat_eamp_monitor2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->stat_eamp_monitor3, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->stat_eamp_monitor4, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->stat_eamp_monitor5, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->stat_eamp_monitor6, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->stat_eamp_monitor7, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->stat_eamp_monitor8, 0u, 0xffu);
    dst_p[8] |= pack_left_shift_u8(src_p->stat_eamp_monitor9, 0u, 0xffu);
    dst_p[9] |= pack_left_shift_u8(src_p->stat_eamp_monitor10, 0u, 0xffu);
    dst_p[10] |= pack_left_shift_u8(src_p->stat_eamp_monitor11, 0u, 0xffu);
    dst_p[11] |= pack_left_shift_u8(src_p->stat_eamp_monitor12, 0u, 0xffu);
    dst_p[12] |= pack_left_shift_u8(src_p->stat_eamp_monitor13, 0u, 0xffu);
    dst_p[13] |= pack_left_shift_u8(src_p->stat_eamp_monitor14, 0u, 0xffu);
    dst_p[14] |= pack_left_shift_u8(src_p->stat_eamp_monitor15, 0u, 0xffu);
    dst_p[15] |= pack_left_shift_u8(src_p->stat_eamp_monitor16, 0u, 0xffu);
    dst_p[16] |= pack_left_shift_u8(src_p->stat_eamp_monitor17, 0u, 0xffu);
    dst_p[17] |= pack_left_shift_u8(src_p->stat_eamp_monitor18, 0u, 0xffu);
    dst_p[18] |= pack_left_shift_u8(src_p->stat_eamp_monitor19, 0u, 0xffu);
    dst_p[19] |= pack_left_shift_u8(src_p->stat_eamp_monitor20, 0u, 0xffu);
    dst_p[20] |= pack_left_shift_u8(src_p->stat_eamp_monitor21, 0u, 0xffu);
    dst_p[21] |= pack_left_shift_u8(src_p->stat_eamp_monitor22, 0u, 0xffu);
    dst_p[22] |= pack_left_shift_u8(src_p->stat_eamp_monitor23, 0u, 0xffu);
    dst_p[23] |= pack_left_shift_u8(src_p->stat_eamp_monitor24, 0u, 0xffu);
    dst_p[24] |= pack_left_shift_u8(src_p->stat_eamp_monitor25, 0u, 0xffu);
    dst_p[25] |= pack_left_shift_u8(src_p->stat_eamp_monitor26, 0u, 0xffu);
    dst_p[26] |= pack_left_shift_u8(src_p->stat_eamp_monitor27, 0u, 0xffu);
    dst_p[27] |= pack_left_shift_u8(src_p->stat_eamp_monitor28, 0u, 0xffu);
    dst_p[28] |= pack_left_shift_u8(src_p->stat_eamp_monitor29, 0u, 0xffu);
    dst_p[29] |= pack_left_shift_u8(src_p->stat_eamp_monitor30, 0u, 0xffu);
    dst_p[30] |= pack_left_shift_u8(src_p->stat_eamp_monitor31, 0u, 0xffu);
    dst_p[31] |= pack_left_shift_u8(src_p->stat_eamp_monitor32, 0u, 0xffu);
    dst_p[32] |= pack_left_shift_u8(src_p->stat_eamp_monitor33, 0u, 0xffu);
    dst_p[33] |= pack_left_shift_u8(src_p->stat_eamp_monitor34, 0u, 0xffu);
    dst_p[34] |= pack_left_shift_u8(src_p->stat_eamp_monitor35, 0u, 0xffu);
    dst_p[35] |= pack_left_shift_u8(src_p->stat_eamp_monitor36, 0u, 0xffu);
    dst_p[36] |= pack_left_shift_u8(src_p->stat_eamp_monitor37, 0u, 0xffu);
    dst_p[37] |= pack_left_shift_u8(src_p->stat_eamp_monitor38, 0u, 0xffu);
    dst_p[38] |= pack_left_shift_u8(src_p->stat_eamp_monitor39, 0u, 0xffu);
    dst_p[39] |= pack_left_shift_u8(src_p->stat_eamp_monitor40, 0u, 0xffu);
    dst_p[40] |= pack_left_shift_u8(src_p->stat_eamp_monitor41, 0u, 0xffu);
    dst_p[41] |= pack_left_shift_u8(src_p->stat_eamp_monitor42, 0u, 0xffu);
    dst_p[42] |= pack_left_shift_u8(src_p->stat_eamp_monitor43, 0u, 0xffu);
    dst_p[43] |= pack_left_shift_u8(src_p->stat_eamp_monitor44, 0u, 0xffu);
    dst_p[44] |= pack_left_shift_u8(src_p->stat_eamp_monitor45, 0u, 0xffu);
    dst_p[45] |= pack_left_shift_u8(src_p->stat_eamp_monitor46, 0u, 0xffu);
    dst_p[46] |= pack_left_shift_u8(src_p->stat_eamp_monitor47, 0u, 0xffu);
    dst_p[47] |= pack_left_shift_u8(src_p->stat_eamp_monitor48, 0u, 0xffu);
    dst_p[48] |= pack_left_shift_u8(src_p->stat_eamp_monitor49, 0u, 0xffu);
    dst_p[49] |= pack_left_shift_u8(src_p->stat_eamp_monitor50, 0u, 0xffu);
    dst_p[50] |= pack_left_shift_u8(src_p->stat_eamp_monitor51, 0u, 0xffu);
    dst_p[51] |= pack_left_shift_u8(src_p->stat_eamp_monitor52, 0u, 0xffu);
    dst_p[52] |= pack_left_shift_u8(src_p->stat_eamp_monitor53, 0u, 0xffu);
    dst_p[53] |= pack_left_shift_u8(src_p->stat_eamp_monitor54, 0u, 0xffu);
    dst_p[54] |= pack_left_shift_u8(src_p->stat_eamp_monitor55, 0u, 0xffu);
    dst_p[55] |= pack_left_shift_u8(src_p->stat_eamp_monitor56, 0u, 0xffu);
    dst_p[56] |= pack_left_shift_u8(src_p->stat_eamp_monitor57, 0u, 0xffu);
    dst_p[57] |= pack_left_shift_u8(src_p->stat_eamp_monitor58, 0u, 0xffu);
    dst_p[58] |= pack_left_shift_u8(src_p->stat_eamp_monitor59, 0u, 0xffu);
    dst_p[59] |= pack_left_shift_u8(src_p->stat_eamp_monitor60, 0u, 0xffu);
    dst_p[60] |= pack_left_shift_u8(src_p->stat_eamp_monitor61, 0u, 0xffu);
    dst_p[61] |= pack_left_shift_u8(src_p->stat_eamp_monitor62, 0u, 0xffu);
    dst_p[62] |= pack_left_shift_u8(src_p->stat_eamp_monitor63, 0u, 0xffu);
    dst_p[63] |= pack_left_shift_u8(src_p->stat_eamp_monitor64, 0u, 0xffu);

    return (64);
}

int canfd_a2_b_eamp_4_unpack(
    canfd_a2_b_eamp_4_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->stat_eamp_monitor1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->stat_eamp_monitor2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->stat_eamp_monitor3 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->stat_eamp_monitor4 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->stat_eamp_monitor5 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->stat_eamp_monitor6 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->stat_eamp_monitor7 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->stat_eamp_monitor8 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);
    dst_p->stat_eamp_monitor9 = unpack_right_shift_u8(src_p[8], 0u, 0xffu);
    dst_p->stat_eamp_monitor10 = unpack_right_shift_u8(src_p[9], 0u, 0xffu);
    dst_p->stat_eamp_monitor11 = unpack_right_shift_u8(src_p[10], 0u, 0xffu);
    dst_p->stat_eamp_monitor12 = unpack_right_shift_u8(src_p[11], 0u, 0xffu);
    dst_p->stat_eamp_monitor13 = unpack_right_shift_u8(src_p[12], 0u, 0xffu);
    dst_p->stat_eamp_monitor14 = unpack_right_shift_u8(src_p[13], 0u, 0xffu);
    dst_p->stat_eamp_monitor15 = unpack_right_shift_u8(src_p[14], 0u, 0xffu);
    dst_p->stat_eamp_monitor16 = unpack_right_shift_u8(src_p[15], 0u, 0xffu);
    dst_p->stat_eamp_monitor17 = unpack_right_shift_u8(src_p[16], 0u, 0xffu);
    dst_p->stat_eamp_monitor18 = unpack_right_shift_u8(src_p[17], 0u, 0xffu);
    dst_p->stat_eamp_monitor19 = unpack_right_shift_u8(src_p[18], 0u, 0xffu);
    dst_p->stat_eamp_monitor20 = unpack_right_shift_u8(src_p[19], 0u, 0xffu);
    dst_p->stat_eamp_monitor21 = unpack_right_shift_u8(src_p[20], 0u, 0xffu);
    dst_p->stat_eamp_monitor22 = unpack_right_shift_u8(src_p[21], 0u, 0xffu);
    dst_p->stat_eamp_monitor23 = unpack_right_shift_u8(src_p[22], 0u, 0xffu);
    dst_p->stat_eamp_monitor24 = unpack_right_shift_u8(src_p[23], 0u, 0xffu);
    dst_p->stat_eamp_monitor25 = unpack_right_shift_u8(src_p[24], 0u, 0xffu);
    dst_p->stat_eamp_monitor26 = unpack_right_shift_u8(src_p[25], 0u, 0xffu);
    dst_p->stat_eamp_monitor27 = unpack_right_shift_u8(src_p[26], 0u, 0xffu);
    dst_p->stat_eamp_monitor28 = unpack_right_shift_u8(src_p[27], 0u, 0xffu);
    dst_p->stat_eamp_monitor29 = unpack_right_shift_u8(src_p[28], 0u, 0xffu);
    dst_p->stat_eamp_monitor30 = unpack_right_shift_u8(src_p[29], 0u, 0xffu);
    dst_p->stat_eamp_monitor31 = unpack_right_shift_u8(src_p[30], 0u, 0xffu);
    dst_p->stat_eamp_monitor32 = unpack_right_shift_u8(src_p[31], 0u, 0xffu);
    dst_p->stat_eamp_monitor33 = unpack_right_shift_u8(src_p[32], 0u, 0xffu);
    dst_p->stat_eamp_monitor34 = unpack_right_shift_u8(src_p[33], 0u, 0xffu);
    dst_p->stat_eamp_monitor35 = unpack_right_shift_u8(src_p[34], 0u, 0xffu);
    dst_p->stat_eamp_monitor36 = unpack_right_shift_u8(src_p[35], 0u, 0xffu);
    dst_p->stat_eamp_monitor37 = unpack_right_shift_u8(src_p[36], 0u, 0xffu);
    dst_p->stat_eamp_monitor38 = unpack_right_shift_u8(src_p[37], 0u, 0xffu);
    dst_p->stat_eamp_monitor39 = unpack_right_shift_u8(src_p[38], 0u, 0xffu);
    dst_p->stat_eamp_monitor40 = unpack_right_shift_u8(src_p[39], 0u, 0xffu);
    dst_p->stat_eamp_monitor41 = unpack_right_shift_u8(src_p[40], 0u, 0xffu);
    dst_p->stat_eamp_monitor42 = unpack_right_shift_u8(src_p[41], 0u, 0xffu);
    dst_p->stat_eamp_monitor43 = unpack_right_shift_u8(src_p[42], 0u, 0xffu);
    dst_p->stat_eamp_monitor44 = unpack_right_shift_u8(src_p[43], 0u, 0xffu);
    dst_p->stat_eamp_monitor45 = unpack_right_shift_u8(src_p[44], 0u, 0xffu);
    dst_p->stat_eamp_monitor46 = unpack_right_shift_u8(src_p[45], 0u, 0xffu);
    dst_p->stat_eamp_monitor47 = unpack_right_shift_u8(src_p[46], 0u, 0xffu);
    dst_p->stat_eamp_monitor48 = unpack_right_shift_u8(src_p[47], 0u, 0xffu);
    dst_p->stat_eamp_monitor49 = unpack_right_shift_u8(src_p[48], 0u, 0xffu);
    dst_p->stat_eamp_monitor50 = unpack_right_shift_u8(src_p[49], 0u, 0xffu);
    dst_p->stat_eamp_monitor51 = unpack_right_shift_u8(src_p[50], 0u, 0xffu);
    dst_p->stat_eamp_monitor52 = unpack_right_shift_u8(src_p[51], 0u, 0xffu);
    dst_p->stat_eamp_monitor53 = unpack_right_shift_u8(src_p[52], 0u, 0xffu);
    dst_p->stat_eamp_monitor54 = unpack_right_shift_u8(src_p[53], 0u, 0xffu);
    dst_p->stat_eamp_monitor55 = unpack_right_shift_u8(src_p[54], 0u, 0xffu);
    dst_p->stat_eamp_monitor56 = unpack_right_shift_u8(src_p[55], 0u, 0xffu);
    dst_p->stat_eamp_monitor57 = unpack_right_shift_u8(src_p[56], 0u, 0xffu);
    dst_p->stat_eamp_monitor58 = unpack_right_shift_u8(src_p[57], 0u, 0xffu);
    dst_p->stat_eamp_monitor59 = unpack_right_shift_u8(src_p[58], 0u, 0xffu);
    dst_p->stat_eamp_monitor60 = unpack_right_shift_u8(src_p[59], 0u, 0xffu);
    dst_p->stat_eamp_monitor61 = unpack_right_shift_u8(src_p[60], 0u, 0xffu);
    dst_p->stat_eamp_monitor62 = unpack_right_shift_u8(src_p[61], 0u, 0xffu);
    dst_p->stat_eamp_monitor63 = unpack_right_shift_u8(src_p[62], 0u, 0xffu);
    dst_p->stat_eamp_monitor64 = unpack_right_shift_u8(src_p[63], 0u, 0xffu);

    return (0);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor5_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor6_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor7_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor8_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor9_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor10_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor11_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor12_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor13_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor14_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor15_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor16_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor17_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor18_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor19_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor20_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor21_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor22_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor23_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor24_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor25_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor26_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor27_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor28_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor29_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor30_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor31_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor32_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor33_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor34_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor35_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor36_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor37_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor38_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor39_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor40_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor41_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor42_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor43_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor44_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor45_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor46_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor47_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor48_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor49_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor50_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor51_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor52_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor53_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor54_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor55_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor56_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor57_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor58_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor59_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor60_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor61_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor62_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor63_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_4_stat_eamp_monitor64_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int canfd_a2_b_eamp_remote_diag_pack(
    uint8_t *dst_p,
    canfd_a2_b_eamp_remote_diag_t *src_p,
    uint8_t size)
{
    if (size < 32u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 32);

    dst_p[0] |= pack_left_shift_u8(src_p->eamp_total_fault_num, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->eamp_supplier_num, 5u, 0xe0u);
    dst_p[1] |= pack_left_shift_u8(src_p->eamp_frame_index, 0u, 0x1fu);
    dst_p[2] |= pack_right_shift_u16(src_p->eamp_fault_num1, 4u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->eamp_fault_num1, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(src_p->eamp_fault_num2, 8u, 0x0fu);
    dst_p[4] |= pack_left_shift_u16(src_p->eamp_fault_num2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->eamp_fault_num3, 4u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->eamp_fault_num3, 4u, 0xf0u);
    dst_p[6] |= pack_right_shift_u16(src_p->eamp_fault_num4, 8u, 0x0fu);
    dst_p[7] |= pack_left_shift_u16(src_p->eamp_fault_num4, 0u, 0xffu);
    dst_p[8] |= pack_right_shift_u16(src_p->eamp_fault_num5, 4u, 0xffu);
    dst_p[9] |= pack_left_shift_u16(src_p->eamp_fault_num5, 4u, 0xf0u);
    dst_p[9] |= pack_right_shift_u16(src_p->eamp_fault_num6, 8u, 0x0fu);
    dst_p[10] |= pack_left_shift_u16(src_p->eamp_fault_num6, 0u, 0xffu);
    dst_p[11] |= pack_right_shift_u16(src_p->eamp_fault_num7, 4u, 0xffu);
    dst_p[12] |= pack_left_shift_u16(src_p->eamp_fault_num7, 4u, 0xf0u);
    dst_p[12] |= pack_right_shift_u16(src_p->eamp_fault_num8, 8u, 0x0fu);
    dst_p[13] |= pack_left_shift_u16(src_p->eamp_fault_num8, 0u, 0xffu);
    dst_p[14] |= pack_right_shift_u16(src_p->eamp_fault_num9, 4u, 0xffu);
    dst_p[15] |= pack_left_shift_u16(src_p->eamp_fault_num9, 4u, 0xf0u);
    dst_p[15] |= pack_right_shift_u16(src_p->eamp_fault_num10, 8u, 0x0fu);
    dst_p[16] |= pack_left_shift_u16(src_p->eamp_fault_num10, 0u, 0xffu);
    dst_p[17] |= pack_right_shift_u16(src_p->eamp_fault_num11, 4u, 0xffu);
    dst_p[18] |= pack_left_shift_u16(src_p->eamp_fault_num11, 4u, 0xf0u);
    dst_p[18] |= pack_right_shift_u16(src_p->eamp_fault_num12, 8u, 0x0fu);
    dst_p[19] |= pack_left_shift_u16(src_p->eamp_fault_num12, 0u, 0xffu);
    dst_p[20] |= pack_right_shift_u16(src_p->eamp_fault_num13, 4u, 0xffu);
    dst_p[21] |= pack_left_shift_u16(src_p->eamp_fault_num13, 4u, 0xf0u);
    dst_p[21] |= pack_right_shift_u16(src_p->eamp_fault_num14, 8u, 0x0fu);
    dst_p[22] |= pack_left_shift_u16(src_p->eamp_fault_num14, 0u, 0xffu);
    dst_p[23] |= pack_right_shift_u16(src_p->eamp_fault_num15, 4u, 0xffu);
    dst_p[24] |= pack_left_shift_u16(src_p->eamp_fault_num15, 4u, 0xf0u);
    dst_p[24] |= pack_right_shift_u16(src_p->eamp_fault_num16, 8u, 0x0fu);
    dst_p[25] |= pack_left_shift_u16(src_p->eamp_fault_num16, 0u, 0xffu);
    dst_p[26] |= pack_right_shift_u16(src_p->eamp_fault_num17, 4u, 0xffu);
    dst_p[27] |= pack_left_shift_u16(src_p->eamp_fault_num17, 4u, 0xf0u);
    dst_p[27] |= pack_right_shift_u16(src_p->eamp_fault_num18, 8u, 0x0fu);
    dst_p[28] |= pack_left_shift_u16(src_p->eamp_fault_num18, 0u, 0xffu);
    dst_p[29] |= pack_right_shift_u16(src_p->eamp_fault_num19, 4u, 0xffu);
    dst_p[30] |= pack_left_shift_u16(src_p->eamp_fault_num19, 4u, 0xf0u);
    dst_p[30] |= pack_right_shift_u16(src_p->eamp_fault_num20, 8u, 0x0fu);
    dst_p[31] |= pack_left_shift_u16(src_p->eamp_fault_num20, 0u, 0xffu);

    return (32);
}

int canfd_a2_b_eamp_remote_diag_unpack(
    canfd_a2_b_eamp_remote_diag_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 32u) {
        return (-EINVAL);
    }

    dst_p->eamp_total_fault_num = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->eamp_supplier_num = unpack_right_shift_u8(src_p[1], 5u, 0xe0u);
    dst_p->eamp_frame_index = unpack_right_shift_u8(src_p[1], 0u, 0x1fu);
    dst_p->eamp_fault_num1 = unpack_left_shift_u16(src_p[2], 4u, 0xffu);
    dst_p->eamp_fault_num1 |= unpack_right_shift_u16(src_p[3], 4u, 0xf0u);
    dst_p->eamp_fault_num2 = unpack_left_shift_u16(src_p[3], 8u, 0x0fu);
    dst_p->eamp_fault_num2 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->eamp_fault_num3 = unpack_left_shift_u16(src_p[5], 4u, 0xffu);
    dst_p->eamp_fault_num3 |= unpack_right_shift_u16(src_p[6], 4u, 0xf0u);
    dst_p->eamp_fault_num4 = unpack_left_shift_u16(src_p[6], 8u, 0x0fu);
    dst_p->eamp_fault_num4 |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);
    dst_p->eamp_fault_num5 = unpack_left_shift_u16(src_p[8], 4u, 0xffu);
    dst_p->eamp_fault_num5 |= unpack_right_shift_u16(src_p[9], 4u, 0xf0u);
    dst_p->eamp_fault_num6 = unpack_left_shift_u16(src_p[9], 8u, 0x0fu);
    dst_p->eamp_fault_num6 |= unpack_right_shift_u16(src_p[10], 0u, 0xffu);
    dst_p->eamp_fault_num7 = unpack_left_shift_u16(src_p[11], 4u, 0xffu);
    dst_p->eamp_fault_num7 |= unpack_right_shift_u16(src_p[12], 4u, 0xf0u);
    dst_p->eamp_fault_num8 = unpack_left_shift_u16(src_p[12], 8u, 0x0fu);
    dst_p->eamp_fault_num8 |= unpack_right_shift_u16(src_p[13], 0u, 0xffu);
    dst_p->eamp_fault_num9 = unpack_left_shift_u16(src_p[14], 4u, 0xffu);
    dst_p->eamp_fault_num9 |= unpack_right_shift_u16(src_p[15], 4u, 0xf0u);
    dst_p->eamp_fault_num10 = unpack_left_shift_u16(src_p[15], 8u, 0x0fu);
    dst_p->eamp_fault_num10 |= unpack_right_shift_u16(src_p[16], 0u, 0xffu);
    dst_p->eamp_fault_num11 = unpack_left_shift_u16(src_p[17], 4u, 0xffu);
    dst_p->eamp_fault_num11 |= unpack_right_shift_u16(src_p[18], 4u, 0xf0u);
    dst_p->eamp_fault_num12 = unpack_left_shift_u16(src_p[18], 8u, 0x0fu);
    dst_p->eamp_fault_num12 |= unpack_right_shift_u16(src_p[19], 0u, 0xffu);
    dst_p->eamp_fault_num13 = unpack_left_shift_u16(src_p[20], 4u, 0xffu);
    dst_p->eamp_fault_num13 |= unpack_right_shift_u16(src_p[21], 4u, 0xf0u);
    dst_p->eamp_fault_num14 = unpack_left_shift_u16(src_p[21], 8u, 0x0fu);
    dst_p->eamp_fault_num14 |= unpack_right_shift_u16(src_p[22], 0u, 0xffu);
    dst_p->eamp_fault_num15 = unpack_left_shift_u16(src_p[23], 4u, 0xffu);
    dst_p->eamp_fault_num15 |= unpack_right_shift_u16(src_p[24], 4u, 0xf0u);
    dst_p->eamp_fault_num16 = unpack_left_shift_u16(src_p[24], 8u, 0x0fu);
    dst_p->eamp_fault_num16 |= unpack_right_shift_u16(src_p[25], 0u, 0xffu);
    dst_p->eamp_fault_num17 = unpack_left_shift_u16(src_p[26], 4u, 0xffu);
    dst_p->eamp_fault_num17 |= unpack_right_shift_u16(src_p[27], 4u, 0xf0u);
    dst_p->eamp_fault_num18 = unpack_left_shift_u16(src_p[27], 8u, 0x0fu);
    dst_p->eamp_fault_num18 |= unpack_right_shift_u16(src_p[28], 0u, 0xffu);
    dst_p->eamp_fault_num19 = unpack_left_shift_u16(src_p[29], 4u, 0xffu);
    dst_p->eamp_fault_num19 |= unpack_right_shift_u16(src_p[30], 4u, 0xf0u);
    dst_p->eamp_fault_num20 = unpack_left_shift_u16(src_p[30], 8u, 0x0fu);
    dst_p->eamp_fault_num20 |= unpack_right_shift_u16(src_p[31], 0u, 0xffu);

    return (0);
}

bool canfd_a2_b_eamp_remote_diag_eamp_total_fault_num_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_eamp_remote_diag_eamp_supplier_num_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_frame_index_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num1_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num2_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num3_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num4_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num5_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num6_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num7_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num8_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num9_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num10_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num11_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num12_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num13_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num14_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num15_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num16_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num17_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num18_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num19_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

bool canfd_a2_b_eamp_remote_diag_eamp_fault_num20_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int canfd_a2_b_eamp_tx_pack(
    uint8_t *dst_p,
    canfd_a2_b_eamp_tx_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_right_shift_u64(src_p->eamp_ceshi_tx, 56u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->eamp_ceshi_tx, 48u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->eamp_ceshi_tx, 40u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->eamp_ceshi_tx, 32u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->eamp_ceshi_tx, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->eamp_ceshi_tx, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->eamp_ceshi_tx, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u64(src_p->eamp_ceshi_tx, 0u, 0xffu);

    return (64);
}

int canfd_a2_b_eamp_tx_unpack(
    canfd_a2_b_eamp_tx_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->eamp_ceshi_tx = unpack_left_shift_u64(src_p[0], 56u, 0xffu);
    dst_p->eamp_ceshi_tx |= unpack_left_shift_u64(src_p[1], 48u, 0xffu);
    dst_p->eamp_ceshi_tx |= unpack_left_shift_u64(src_p[2], 40u, 0xffu);
    dst_p->eamp_ceshi_tx |= unpack_left_shift_u64(src_p[3], 32u, 0xffu);
    dst_p->eamp_ceshi_tx |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
    dst_p->eamp_ceshi_tx |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->eamp_ceshi_tx |= unpack_left_shift_u64(src_p[6], 8u, 0xffu);
    dst_p->eamp_ceshi_tx |= unpack_right_shift_u64(src_p[7], 0u, 0xffu);

    return (0);
}

bool canfd_a2_b_eamp_tx_eamp_ceshi_tx_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int canfd_a2_b_eamp_rx_pack(
    uint8_t *dst_p,
    canfd_a2_b_eamp_rx_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_right_shift_u64(src_p->eamp_ceshi_rx, 56u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->eamp_ceshi_rx, 48u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->eamp_ceshi_rx, 40u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->eamp_ceshi_rx, 32u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->eamp_ceshi_rx, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->eamp_ceshi_rx, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->eamp_ceshi_rx, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u64(src_p->eamp_ceshi_rx, 0u, 0xffu);

    return (64);
}

int canfd_a2_b_eamp_rx_unpack(
    canfd_a2_b_eamp_rx_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->eamp_ceshi_rx = unpack_left_shift_u64(src_p[0], 56u, 0xffu);
    dst_p->eamp_ceshi_rx |= unpack_left_shift_u64(src_p[1], 48u, 0xffu);
    dst_p->eamp_ceshi_rx |= unpack_left_shift_u64(src_p[2], 40u, 0xffu);
    dst_p->eamp_ceshi_rx |= unpack_left_shift_u64(src_p[3], 32u, 0xffu);
    dst_p->eamp_ceshi_rx |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
    dst_p->eamp_ceshi_rx |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->eamp_ceshi_rx |= unpack_left_shift_u64(src_p[6], 8u, 0xffu);
    dst_p->eamp_ceshi_rx |= unpack_right_shift_u64(src_p[7], 0u, 0xffu);

    return (0);
}

bool canfd_a2_b_eamp_rx_eamp_ceshi_rx_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int canfd_a2_b_n_mm_eamp_pack(
    uint8_t *dst_p,
    canfd_a2_b_n_mm_eamp_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->src_node_id_eamp, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->n_mm_eamp_reserved1, 1u, 0xfeu);
    dst_p[1] |= pack_left_shift_u8(src_p->rmr_eamp, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->eamp_wakeup_diag, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->eamp_wakeup_nm, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->eamp_wakeup_poweron, 0u, 0x01u);
    dst_p[5] |= pack_left_shift_u8(src_p->eamp_awake_diag, 2u, 0x04u);
    dst_p[5] |= pack_left_shift_u8(src_p->eamp_awake_nm, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->eamp_awake_poweron, 0u, 0x01u);

    return (8);
}

int canfd_a2_b_n_mm_eamp_unpack(
    canfd_a2_b_n_mm_eamp_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->src_node_id_eamp = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->n_mm_eamp_reserved1 = unpack_right_shift_u8(src_p[1], 1u, 0xfeu);
    dst_p->rmr_eamp = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->eamp_wakeup_diag = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->eamp_wakeup_nm = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->eamp_wakeup_poweron = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->eamp_awake_diag = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->eamp_awake_nm = unpack_right_shift_u8(src_p[5], 1u, 0x02u);
    dst_p->eamp_awake_poweron = unpack_right_shift_u8(src_p[5], 0u, 0x01u);

    return (0);
}

bool canfd_a2_b_n_mm_eamp_src_node_id_eamp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool canfd_a2_b_n_mm_eamp_n_mm_eamp_reserved1_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

bool canfd_a2_b_n_mm_eamp_rmr_eamp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool canfd_a2_b_n_mm_eamp_eamp_wakeup_diag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool canfd_a2_b_n_mm_eamp_eamp_wakeup_nm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool canfd_a2_b_n_mm_eamp_eamp_wakeup_poweron_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool canfd_a2_b_n_mm_eamp_eamp_awake_diag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool canfd_a2_b_n_mm_eamp_eamp_awake_nm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool canfd_a2_b_n_mm_eamp_eamp_awake_poweron_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int canfd_a2_b_diag_eamp_res_pack(
    uint8_t *dst_p,
    canfd_a2_b_diag_eamp_res_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_right_shift_u64(src_p->diag_eamp_res, 56u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->diag_eamp_res, 48u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->diag_eamp_res, 40u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->diag_eamp_res, 32u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->diag_eamp_res, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->diag_eamp_res, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->diag_eamp_res, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u64(src_p->diag_eamp_res, 0u, 0xffu);

    return (64);
}

int canfd_a2_b_diag_eamp_res_unpack(
    canfd_a2_b_diag_eamp_res_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->diag_eamp_res = unpack_left_shift_u64(src_p[0], 56u, 0xffu);
    dst_p->diag_eamp_res |= unpack_left_shift_u64(src_p[1], 48u, 0xffu);
    dst_p->diag_eamp_res |= unpack_left_shift_u64(src_p[2], 40u, 0xffu);
    dst_p->diag_eamp_res |= unpack_left_shift_u64(src_p[3], 32u, 0xffu);
    dst_p->diag_eamp_res |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
    dst_p->diag_eamp_res |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->diag_eamp_res |= unpack_left_shift_u64(src_p[6], 8u, 0xffu);
    dst_p->diag_eamp_res |= unpack_right_shift_u64(src_p[7], 0u, 0xffu);

    return (0);
}

bool canfd_a2_b_diag_eamp_res_diag_eamp_res_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int canfd_a2_b_diag_eamp_req_pack(
    uint8_t *dst_p,
    canfd_a2_b_diag_eamp_req_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_right_shift_u64(src_p->diag_eamp_req, 56u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->diag_eamp_req, 48u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->diag_eamp_req, 40u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->diag_eamp_req, 32u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->diag_eamp_req, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->diag_eamp_req, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->diag_eamp_req, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u64(src_p->diag_eamp_req, 0u, 0xffu);

    return (64);
}

int canfd_a2_b_diag_eamp_req_unpack(
    canfd_a2_b_diag_eamp_req_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->diag_eamp_req = unpack_left_shift_u64(src_p[0], 56u, 0xffu);
    dst_p->diag_eamp_req |= unpack_left_shift_u64(src_p[1], 48u, 0xffu);
    dst_p->diag_eamp_req |= unpack_left_shift_u64(src_p[2], 40u, 0xffu);
    dst_p->diag_eamp_req |= unpack_left_shift_u64(src_p[3], 32u, 0xffu);
    dst_p->diag_eamp_req |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
    dst_p->diag_eamp_req |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->diag_eamp_req |= unpack_left_shift_u64(src_p[6], 8u, 0xffu);
    dst_p->diag_eamp_req |= unpack_right_shift_u64(src_p[7], 0u, 0xffu);

    return (0);
}

bool canfd_a2_b_diag_eamp_req_diag_eamp_req_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int canfd_a2_b_icc_ic_2_pack(
    uint8_t *dst_p,
    canfd_a2_b_icc_ic_2_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->stat_amp_alarm, 2u, 0xfcu);

    return (8);
}

int canfd_a2_b_icc_ic_2_unpack(
    canfd_a2_b_icc_ic_2_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->stat_amp_alarm = unpack_right_shift_u8(src_p[0], 2u, 0xfcu);

    return (0);
}

bool canfd_a2_b_icc_ic_2_stat_amp_alarm_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

int canfd_a2_b_icc_ic_9_pack(
    uint8_t *dst_p,
    canfd_a2_b_icc_ic_9_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->set_ampvr_volume, 4u, 0xf0u);
    dst_p[0] |= pack_left_shift_u8(src_p->set_amp_navi_volume, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->set_amp_media_volume, 2u, 0xfcu);
    dst_p[1] |= pack_left_shift_u8(src_p->set_amp_key_tone, 0u, 0x03u);
    dst_p[2] |= pack_left_shift_u8(src_p->set_amp_sound_focus, 5u, 0xe0u);
    dst_p[2] |= pack_left_shift_u8(src_p->set_amp_phone_volume, 0u, 0x1fu);
    dst_p[3] |= pack_left_shift_u8(src_p->set_amp_sound_effect_bass, 4u, 0xf0u);
    dst_p[3] |= pack_left_shift_u8(src_p->set_amp_sound_effect, 0u, 0x0fu);
    dst_p[4] |= pack_left_shift_u8(src_p->set_amp_sound_effect_treble, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u8(src_p->set_amp_sound_effect_midrange, 0u, 0x0fu);
    dst_p[5] |= pack_left_shift_u8(src_p->set_amp_sound_field_fader, 4u, 0xf0u);
    dst_p[5] |= pack_left_shift_u8(src_p->set_amp_sound_field_balance, 0u, 0x0fu);
    dst_p[6] |= pack_left_shift_u8(src_p->set_headrest_mode, 6u, 0xc0u);
    dst_p[7] |= pack_left_shift_u8(src_p->set_virtual_sbwfr_on_off, 6u, 0xc0u);
    dst_p[7] |= pack_left_shift_u8(src_p->set_surnd_fn_on_off, 4u, 0x30u);

    return (8);
}

int canfd_a2_b_icc_ic_9_unpack(
    canfd_a2_b_icc_ic_9_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->set_ampvr_volume = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);
    dst_p->set_amp_navi_volume = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->set_amp_media_volume = unpack_right_shift_u8(src_p[1], 2u, 0xfcu);
    dst_p->set_amp_key_tone = unpack_right_shift_u8(src_p[1], 0u, 0x03u);
    dst_p->set_amp_sound_focus = unpack_right_shift_u8(src_p[2], 5u, 0xe0u);
    dst_p->set_amp_phone_volume = unpack_right_shift_u8(src_p[2], 0u, 0x1fu);
    dst_p->set_amp_sound_effect_bass = unpack_right_shift_u8(src_p[3], 4u, 0xf0u);
    dst_p->set_amp_sound_effect = unpack_right_shift_u8(src_p[3], 0u, 0x0fu);
    dst_p->set_amp_sound_effect_treble = unpack_right_shift_u8(src_p[4], 4u, 0xf0u);
    dst_p->set_amp_sound_effect_midrange = unpack_right_shift_u8(src_p[4], 0u, 0x0fu);
    dst_p->set_amp_sound_field_fader = unpack_right_shift_u8(src_p[5], 4u, 0xf0u);
    dst_p->set_amp_sound_field_balance = unpack_right_shift_u8(src_p[5], 0u, 0x0fu);
    dst_p->set_headrest_mode = unpack_right_shift_u8(src_p[6], 6u, 0xc0u);
    dst_p->set_virtual_sbwfr_on_off = unpack_right_shift_u8(src_p[7], 6u, 0xc0u);
    dst_p->set_surnd_fn_on_off = unpack_right_shift_u8(src_p[7], 4u, 0x30u);

    return (0);
}

bool canfd_a2_b_icc_ic_9_set_ampvr_volume_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_9_set_amp_navi_volume_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_9_set_amp_media_volume_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_icc_ic_9_set_amp_key_tone_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_9_set_amp_sound_focus_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool canfd_a2_b_icc_ic_9_set_amp_phone_volume_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

bool canfd_a2_b_icc_ic_9_set_amp_sound_effect_bass_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_9_set_amp_sound_effect_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_9_set_amp_sound_effect_treble_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_9_set_amp_sound_effect_midrange_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_9_set_amp_sound_field_fader_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_9_set_amp_sound_field_balance_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_9_set_headrest_mode_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_9_set_virtual_sbwfr_on_off_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool canfd_a2_b_icc_ic_9_set_surnd_fn_on_off_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int canfd_a2_b_icc_ic_10_pack(
    uint8_t *dst_p,
    canfd_a2_b_icc_ic_10_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->set_amp_mute, 6u, 0xc0u);
    dst_p[0] |= pack_left_shift_u8(src_p->set_amp_speed_volume, 3u, 0x38u);
    dst_p[0] |= pack_left_shift_u8(src_p->set_amp_media_duck, 0u, 0x03u);
    dst_p[1] |= pack_left_shift_u8(src_p->req_ampa2_btts_sound, 6u, 0xc0u);
    dst_p[1] |= pack_left_shift_u8(src_p->req_ampa2_bvr_sound, 4u, 0x30u);
    dst_p[1] |= pack_left_shift_u8(src_p->req_ampa2_b_navi_sound, 2u, 0x0cu);
    dst_p[1] |= pack_left_shift_u8(src_p->req_ampa2_b_media_sound, 0u, 0x03u);
    dst_p[2] |= pack_left_shift_u8(src_p->req_ampa2_b_key_tone, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->req_ampa2_b_phone_sound, 6u, 0xc0u);
    dst_p[3] |= pack_left_shift_u8(src_p->set_amp_alarm_volume, 2u, 0x3cu);
    dst_p[3] |= pack_left_shift_u8(src_p->set_amp_restore_defaults, 0u, 0x03u);
    dst_p[4] |= pack_left_shift_u8(src_p->set_amp_sound_effect_mid_bass, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u8(src_p->set_amp_sound_effect_mega_bass, 0u, 0x0fu);
    dst_p[5] |= pack_left_shift_u8(src_p->set_ampa2_b_config, 6u, 0xc0u);
    dst_p[5] |= pack_left_shift_u8(src_p->set_amp_sound_bypass, 4u, 0x30u);
    dst_p[5] |= pack_left_shift_u8(src_p->set_amp_sound_effect_mid_treble, 0u, 0x0fu);
    dst_p[6] |= pack_left_shift_u8(src_p->set_amp_background_volume, 0u, 0x3fu);

    return (8);
}

int canfd_a2_b_icc_ic_10_unpack(
    canfd_a2_b_icc_ic_10_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->set_amp_mute = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->set_amp_speed_volume = unpack_right_shift_u8(src_p[0], 3u, 0x38u);
    dst_p->set_amp_media_duck = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->req_ampa2_btts_sound = unpack_right_shift_u8(src_p[1], 6u, 0xc0u);
    dst_p->req_ampa2_bvr_sound = unpack_right_shift_u8(src_p[1], 4u, 0x30u);
    dst_p->req_ampa2_b_navi_sound = unpack_right_shift_u8(src_p[1], 2u, 0x0cu);
    dst_p->req_ampa2_b_media_sound = unpack_right_shift_u8(src_p[1], 0u, 0x03u);
    dst_p->req_ampa2_b_key_tone = unpack_right_shift_u8(src_p[2], 6u, 0xc0u);
    dst_p->req_ampa2_b_phone_sound = unpack_right_shift_u8(src_p[3], 6u, 0xc0u);
    dst_p->set_amp_alarm_volume = unpack_right_shift_u8(src_p[3], 2u, 0x3cu);
    dst_p->set_amp_restore_defaults = unpack_right_shift_u8(src_p[3], 0u, 0x03u);
    dst_p->set_amp_sound_effect_mid_bass = unpack_right_shift_u8(src_p[4], 4u, 0xf0u);
    dst_p->set_amp_sound_effect_mega_bass = unpack_right_shift_u8(src_p[4], 0u, 0x0fu);
    dst_p->set_ampa2_b_config = unpack_right_shift_u8(src_p[5], 6u, 0xc0u);
    dst_p->set_amp_sound_bypass = unpack_right_shift_u8(src_p[5], 4u, 0x30u);
    dst_p->set_amp_sound_effect_mid_treble = unpack_right_shift_u8(src_p[5], 0u, 0x0fu);
    dst_p->set_amp_background_volume = unpack_right_shift_u8(src_p[6], 0u, 0x3fu);

    return (0);
}

bool canfd_a2_b_icc_ic_10_set_amp_mute_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_set_amp_speed_volume_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool canfd_a2_b_icc_ic_10_set_amp_media_duck_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_req_ampa2_btts_sound_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_req_ampa2_bvr_sound_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_req_ampa2_b_navi_sound_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_req_ampa2_b_media_sound_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_req_ampa2_b_key_tone_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_req_ampa2_b_phone_sound_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_set_amp_alarm_volume_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_10_set_amp_restore_defaults_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_set_amp_sound_effect_mid_bass_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_10_set_amp_sound_effect_mega_bass_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_10_set_ampa2_b_config_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_set_amp_sound_bypass_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_10_set_amp_sound_effect_mid_treble_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_10_set_amp_background_volume_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

int canfd_a2_b_icc_ic_37_pack(
    uint8_t *dst_p,
    canfd_a2_b_icc_ic_37_t *src_p,
    uint8_t size)
{
    if (size < 32u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 32);

    dst_p[5] |= pack_left_shift_u8(src_p->icc_ampa2_benc_sound_req, 6u, 0xc0u);
    dst_p[5] |= pack_left_shift_u8(src_p->icc_ampkt_vvoice_volume_set, 0u, 0x3fu);
    dst_p[6] |= pack_left_shift_u8(src_p->icc_ampa2_b_chime_sound_req, 6u, 0xc0u);
    dst_p[6] |= pack_left_shift_u8(src_p->icc_ampenc_volume_set, 0u, 0x3fu);
    dst_p[7] |= pack_left_shift_u8(src_p->set_amp_sound_focus_2, 4u, 0xf0u);
    dst_p[7] |= pack_left_shift_u8(src_p->icc_ampa2_bkt_vvoice_sound_req, 0u, 0x07u);
    dst_p[10] |= pack_left_shift_u8(src_p->set_amp_loudness, 2u, 0x0cu);
    dst_p[14] |= pack_left_shift_u8(src_p->set_amp_key_volume, 2u, 0xfcu);
    dst_p[14] |= pack_right_shift_u8(src_p->set_amp_ex_soundmode, 1u, 0x03u);
    dst_p[15] |= pack_left_shift_u8(src_p->set_amp_ex_soundmode, 7u, 0x80u);
    dst_p[15] |= pack_left_shift_u8(src_p->set_ampa2_benc_sound, 4u, 0x70u);

    return (32);
}

int canfd_a2_b_icc_ic_37_unpack(
    canfd_a2_b_icc_ic_37_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 32u) {
        return (-EINVAL);
    }

    dst_p->icc_ampa2_benc_sound_req = unpack_right_shift_u8(src_p[5], 6u, 0xc0u);
    dst_p->icc_ampkt_vvoice_volume_set = unpack_right_shift_u8(src_p[5], 0u, 0x3fu);
    dst_p->icc_ampa2_b_chime_sound_req = unpack_right_shift_u8(src_p[6], 6u, 0xc0u);
    dst_p->icc_ampenc_volume_set = unpack_right_shift_u8(src_p[6], 0u, 0x3fu);
    dst_p->set_amp_sound_focus_2 = unpack_right_shift_u8(src_p[7], 4u, 0xf0u);
    dst_p->icc_ampa2_bkt_vvoice_sound_req = unpack_right_shift_u8(src_p[7], 0u, 0x07u);
    dst_p->set_amp_loudness = unpack_right_shift_u8(src_p[10], 2u, 0x0cu);
    dst_p->set_amp_key_volume = unpack_right_shift_u8(src_p[14], 2u, 0xfcu);
    dst_p->set_amp_ex_soundmode = unpack_left_shift_u8(src_p[14], 1u, 0x03u);
    dst_p->set_amp_ex_soundmode |= unpack_right_shift_u8(src_p[15], 7u, 0x80u);
    dst_p->set_ampa2_benc_sound = unpack_right_shift_u8(src_p[15], 4u, 0x70u);

    return (0);
}

bool canfd_a2_b_icc_ic_37_icc_ampa2_benc_sound_req_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_37_icc_ampkt_vvoice_volume_set_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_icc_ic_37_icc_ampa2_b_chime_sound_req_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_37_icc_ampenc_volume_set_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_icc_ic_37_set_amp_sound_focus_2_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool canfd_a2_b_icc_ic_37_icc_ampa2_bkt_vvoice_sound_req_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool canfd_a2_b_icc_ic_37_set_amp_loudness_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

bool canfd_a2_b_icc_ic_37_set_amp_key_volume_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

bool canfd_a2_b_icc_ic_37_set_amp_ex_soundmode_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool canfd_a2_b_icc_ic_37_set_ampa2_benc_sound_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int canfd_a2_b_flzcu_9_pack(
    uint8_t *dst_p,
    canfd_a2_b_flzcu_9_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_left_shift_u8(src_p->flzcu_9_power_mode, 0u, 0x03u);

    return (8);
}

int canfd_a2_b_flzcu_9_unpack(
    canfd_a2_b_flzcu_9_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->flzcu_9_power_mode = unpack_right_shift_u8(src_p[2], 0u, 0x03u);

    return (0);
}

bool canfd_a2_b_flzcu_9_flzcu_9_power_mode_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int canfd_a2_b_vcu_1_g_pack(
    uint8_t *dst_p,
    canfd_a2_b_vcu_1_g_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[7] |= pack_left_shift_u8(src_p->vcu_1_g_prnd_gear_act, 4u, 0x70u);

    return (8);
}

int canfd_a2_b_vcu_1_g_unpack(
    canfd_a2_b_vcu_1_g_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vcu_1_g_prnd_gear_act = unpack_right_shift_u8(src_p[7], 4u, 0x70u);

    return (0);
}

bool canfd_a2_b_vcu_1_g_vcu_1_g_prnd_gear_act_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int canfd_a2_b_obd_req_broadcast_pack(
    uint8_t *dst_p,
    canfd_a2_b_obd_req_broadcast_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 64);

    dst_p[0] |= pack_right_shift_u64(src_p->diag_functional_req, 56u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->diag_functional_req, 48u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->diag_functional_req, 40u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->diag_functional_req, 32u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->diag_functional_req, 24u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->diag_functional_req, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->diag_functional_req, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u64(src_p->diag_functional_req, 0u, 0xffu);

    return (64);
}

int canfd_a2_b_obd_req_broadcast_unpack(
    canfd_a2_b_obd_req_broadcast_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 64u) {
        return (-EINVAL);
    }

    dst_p->diag_functional_req = unpack_left_shift_u64(src_p[0], 56u, 0xffu);
    dst_p->diag_functional_req |= unpack_left_shift_u64(src_p[1], 48u, 0xffu);
    dst_p->diag_functional_req |= unpack_left_shift_u64(src_p[2], 40u, 0xffu);
    dst_p->diag_functional_req |= unpack_left_shift_u64(src_p[3], 32u, 0xffu);
    dst_p->diag_functional_req |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
    dst_p->diag_functional_req |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
    dst_p->diag_functional_req |= unpack_left_shift_u64(src_p[6], 8u, 0xffu);
    dst_p->diag_functional_req |= unpack_right_shift_u64(src_p[7], 0u, 0xffu);

    return (0);
}

bool canfd_a2_b_obd_req_broadcast_diag_functional_req_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int canfd_a2_b_onebox_1_g_pack(
    uint8_t *dst_p,
    canfd_a2_b_onebox_1_g_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_right_shift_u16(src_p->vehicle_speed_vso_sig, 5u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->vehicle_speed_vso_sig, 3u, 0xf8u);
    dst_p[3] |= pack_left_shift_u8(src_p->vehicle_speed_vso_sig_valid_data, 2u, 0x04u);

    return (8);
}

int canfd_a2_b_onebox_1_g_unpack(
    canfd_a2_b_onebox_1_g_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vehicle_speed_vso_sig = unpack_left_shift_u16(src_p[2], 5u, 0xffu);
    dst_p->vehicle_speed_vso_sig |= unpack_right_shift_u16(src_p[3], 3u, 0xf8u);
    dst_p->vehicle_speed_vso_sig_valid_data = unpack_right_shift_u8(src_p[3], 2u, 0x04u);

    return (0);
}

bool canfd_a2_b_onebox_1_g_vehicle_speed_vso_sig_is_in_range(uint16_t value)
{
    return (value <= 8190u);
}

bool canfd_a2_b_onebox_1_g_vehicle_speed_vso_sig_valid_data_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int canfd_a2_b_ems_1_g_pack(
    uint8_t *dst_p,
    canfd_a2_b_ems_1_g_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[6] |= pack_left_shift_u8(src_p->ems_engine_sts_actual, 5u, 0x20u);

    return (8);
}

int canfd_a2_b_ems_1_g_unpack(
    canfd_a2_b_ems_1_g_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ems_engine_sts_actual = unpack_right_shift_u8(src_p[6], 5u, 0x20u);

    return (0);
}

bool canfd_a2_b_ems_1_g_ems_engine_sts_actual_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int canfd_a2_b_tms_1_pack(
    uint8_t *dst_p,
    canfd_a2_b_tms_1_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[5] |= pack_left_shift_u8(src_p->blow_speed_level_display_sts, 1u, 0x1eu);

    return (8);
}

int canfd_a2_b_tms_1_unpack(
    canfd_a2_b_tms_1_t *dst_p,
    uint8_t *src_p,
    uint8_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->blow_speed_level_display_sts = unpack_right_shift_u8(src_p[5], 1u, 0x1eu);

    return (0);
}

bool canfd_a2_b_tms_1_blow_speed_level_display_sts_is_in_range(uint8_t value)
{
    return (value <= 15u);
}
