#include "uds_user.h"
#include "Dcm_DrvCfg.h"

/******************************************************************************
 *                      Variables                                          *
 ******************************************************************************/
boolean b_Stay_In_Boot_Flag;       /*StayInBoot*/
boolean b_DownLoad_FlashDrv_Flag;
boolean b_Checkapp_Success;


const Struct_Uds_Cfg_Info Uds_Cfg_Info[UDS_SID_NUMBER] =
	{
		{.SID = 0x10U,
		 .Addr_Support = 0x0CU,
		 .Session_Support = DEFALUT_SESSION | PROGRAM_SESSION | EXTEND_SESSION,
		 .Security_En = false,
		 .DL_Min = 2U,
		 .DL_Max = 2U,
		 .SidFunc_Callback = SID_DSC_Analysis},
		{.SID = 0x11U,
		 .Addr_Support = 0x0CU,
		 .Session_Support = DEFALUT_SESSION | PROGRAM_SESSION | EXTEND_SESSION,
		 .Security_En = false,
		 .DL_Min = 2U,
		 .DL_Max = 2U,
		 .SidFunc_Callback = SID_ER_Analysis},
		{.SID = 0x27U,
		 .Addr_Support = 0x0CU,
		 .Session_Support = DEFALUT_SESSION | PROGRAM_SESSION | EXTEND_SESSION,
		 .Security_En = false,
		 .DL_Min = 2U,
		 .DL_Max = 18,
		 .SidFunc_Callback = SID_SA_Analysis},
		{.SID = 0x3EU,
		 .Addr_Support = 0x0CU,
		 .Session_Support = DEFALUT_SESSION | PROGRAM_SESSION | EXTEND_SESSION,
		 .Security_En = false,
		 .DL_Min = 2U,
		 .DL_Max = 2U,
		 .SidFunc_Callback = SID_TP_Analysis},
		{.SID = 0x22U,
		 .Addr_Support = 0x0CU,
		 .Session_Support = DEFALUT_SESSION | PROGRAM_SESSION | EXTEND_SESSION,
		 .Security_En = false,
		 .DL_Min = 3U,
		 .DL_Max = 11U,
		 .SidFunc_Callback = SID_RDBI_Analysis},
		{.SID = 0x2EU,
		 .Addr_Support = 0x04U,
		 .Session_Support = PROGRAM_SESSION,
		 .Security_En = false,
		 .DL_Min = 4U,
		 .DL_Max = 255U,
		 .SidFunc_Callback = SID_WDBI_Analysis},
		{.SID = 0x31U,
		 .Addr_Support = 0x04U,
		 .Session_Support = PROGRAM_SESSION | EXTEND_SESSION,
		 .Security_En = false,
		 .DL_Min = 4U,
		 .DL_Max = 13U,
		 .SidFunc_Callback = SID_RC_Analysis},
		{
		.SID 				= 0x34U,
		.Addr_Support 		= 0x04U,
		.Session_Support 	= PROGRAM_SESSION,
		.Security_En 		= true,
		.DL_Min 			= 11U,
		.DL_Max 			= 11U,
		.SidFunc_Callback 	= SID_RD_Analysis
		},
		{
		.SID 				= 0x36U,
		.Addr_Support 		= 0x04U,
		.Session_Support 	= PROGRAM_SESSION,
		.Security_En 			= true,
		// .DL_Min 			= (256U + 2U),
		.DL_Min 			= (0U + 2U),
//		.DL_Max 			= (1024U + 2U),
		.DL_Max 			= (3840U + 2U),   //2024-10-28
		.SidFunc_Callback 	= SID_TD_Analysis
		},
		{
		.SID 				= 0x37U,
		.Addr_Support 		= 0x04U,
		.Session_Support 	= PROGRAM_SESSION,
		.Security_En 			= true,
		.DL_Min 			= 1U,
		.DL_Max 			= 1U,
		.SidFunc_Callback 	= SID_RTE_Analysis
		},
		{
			.SID = 0x85U,
			.Addr_Support = 0x0CU,
			.Session_Support = EXTEND_SESSION,
			.Security_En = false,
			.DL_Min = 2U,
			.DL_Max = 2U,
			.SidFunc_Callback = SID_CDTCS_Analysis},
		{.SID = 0x28U,
		 .Addr_Support = 0x0CU,
		 .Session_Support = EXTEND_SESSION,
		 .Security_En = false,
		 .DL_Min = 3U,
		 .DL_Max = 3U,
		 .SidFunc_Callback = SID_CC_Analysis},
		{.SID = 0x14U,
		 .Addr_Support = 0x0CU,
		 .Session_Support = DEFALUT_SESSION | EXTEND_SESSION,
		 .Security_En = false,
		 .DL_Min = 4U,
		 .DL_Max = 4U,
		 .SidFunc_Callback = SID_CDTCI_Analysis},
		{.SID = 0x19U,
		 .Addr_Support = 0x0CU,
		 .Session_Support = DEFALUT_SESSION | EXTEND_SESSION,
		 .Security_En = false,
		 .DL_Min = 2U,
		 .DL_Max = 0xFFU,
		 .SidFunc_Callback = SID_RDTCI_Analysis},
};
